{% set name = "clingo-dl" %}
{% set version = "1.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/potassco/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 98f70170a9916e67e8fd247adc3848f73405385b7b6277de528d99d55f8074d1

build:
  number: 2

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - make  # [unix]
    - cmake >=3.24.0
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - clingo >=5.5.1
  run:
    - python
    # clingo breaks the API with minor version increments
    - {{ pin_compatible('clingo', min_pin='x.x', max_pin='x.x') }}
    - cffi  # [python_impl == 'cpython']

test:
  requires:
    - pip
  commands:
    - pip check
    - clingo-dl --version
    - python -m clingodl --version

about:
  home: https://potassco.org/
  license: MIT
  summary: A solver for logic programs with difference constraints.
  description: The clingo-dl solver extends the clingo ASP system with support for difference logic constraints.
  license_file: LICENSE.md
  doc_url: https://potassco.org/
  dev_url: https://github.com/potassco/{{ name }}

extra:
  recipe-maintainers:
    - rkaminsk
